In [1]:
from hfradar.src.radials import Radial
import os


In [2]:
radial_file = '../hfradar/data/radials/ruv/SEAB/RDLi_SEAB_2019_01_01_0100.ruv'


In [3]:
r = Radial(radial_file)

This is a list of all methods of a hfradar.radials.Radial instance.

## Radial File Information
* file_path - String of the file path including the filename
* file_name - String of the filename
* file_type - String of the filetype

## Radial Metadata File
* header - Dictionary of header information
* footer - Dictionary of footer information

## Clean up metadata
* clean_header - Run this if you are planning to insert the radial data into the MySQL database.

## Radial Table Data (Pandas Dataframe)
* data - Dataframe of radial data
* diags_radial - Dataframe of radial diagnostic data
* diags_hardware - Dataframe of radial hardware data

## Quality Control tests
* qc_qartod_syntax (QC06) - QARTOD HF Radar Syntax Test
* qc_qartod_maximum_velocity (QC07) - QARTOD HF Radar Maximum Speed test
* qc_qartod_valid_location (QC08)- QARTOD HF Radar Location test
* qc_qartod_radial_count (QC09) - QARTOD HF Radar Radial Threshold test
* qc_qartod_spatial_median (QC10) - QARTOD HF Radar Spatial Median test
* qc_qartod_temporal_gradient (QC11) - QARTOD HF Radar Temporal Gradient test
* qc_qartod_avg_radial_bearing (QC12) - QARTOD HF Radar Average Radial Bearing test
* qc_qartod_primary_flag - QARTOD Primary Flag

## Export to new file format
* export - Export the Radial instance as either a new ruv file or netcdf by specifying file_type='radial' or 'netcdf' respectively... 
* eg. r.export(filename, file_type='radial')

# Radial File Information

In [4]:
r.file_name

'RDLi_SEAB_2019_01_01_0100.ruv'

In [5]:
r.file_path

'../hfradar/data/radials/ruv/SEAB'

In [6]:
r.file_type()

'radial'

# Radial Metadata Information

We can view the header and footer information in a dictionary format by doing the following:

In [7]:
r.metadata

OrderedDict([('CTF', '1.00'),
             ('FileType', 'LLUV rdls "RadialMap"'),
             ('LLUVSpec', '1.27  2017 01 13'),
             ('UUID', 'DF43E143-E1F6-4CD2-9841-DE9503B48C37'),
             ('Manufacturer', 'CODAR Ocean Sensors. SeaSonde'),
             ('Site', 'SEAB ""'),
             ('TimeStamp', '2019 01 01  01 00 00'),
             ('TimeZone', '"UTC" +0.000 0 "Atlantic/Reykjavik"'),
             ('TimeCoverage', '75.000 Minutes'),
             ('Origin', '40.3668167  -73.9735333'),
             ('GreatCircle', '"WGS84" 6378137.000  298.257223562997'),
             ('GeodVersion', '"CGEO" 1.85  2017 10 05'),
             ('LLUVTrustData', 'all  all lluv xyuv rbvd'),
             ('RangeStart', '2'),
             ('RangeEnd', '23'),
             ('RangeResolutionKMeters', '3.020300'),
             ('RangeCells', '31'),
             ('DopplerCells', '512'),
             ('DopplerInterpolation', '2'),
             ('AntennaBearing', '151.0 True'),
             ('Refer

Next, we can clean up the header dictionary. Validate_header() is specifically coded to clean the header data up so that we can insert it into the database without error

In [ ]:
# r.clean_header()

In [8]:
r.metadata

OrderedDict([('CTF', '1.00'),
             ('FileType', 'LLUV rdls "RadialMap"'),
             ('LLUVSpec', '1.27  2017 01 13'),
             ('UUID', 'DF43E143-E1F6-4CD2-9841-DE9503B48C37'),
             ('Manufacturer', 'CODAR Ocean Sensors. SeaSonde'),
             ('Site', 'SEAB ""'),
             ('TimeStamp', '2019 01 01  01 00 00'),
             ('TimeZone', '"UTC" +0.000 0 "Atlantic/Reykjavik"'),
             ('TimeCoverage', '75.000 Minutes'),
             ('Origin', '40.3668167  -73.9735333'),
             ('GreatCircle', '"WGS84" 6378137.000  298.257223562997'),
             ('GeodVersion', '"CGEO" 1.85  2017 10 05'),
             ('LLUVTrustData', 'all  all lluv xyuv rbvd'),
             ('RangeStart', '2'),
             ('RangeEnd', '23'),
             ('RangeResolutionKMeters', '3.020300'),
             ('RangeCells', '31'),
             ('DopplerCells', '512'),
             ('DopplerInterpolation', '2'),
             ('AntennaBearing', '151.0 True'),
             ('Refer

# Radial Table Data
Dataframes will start with an index automatically generated by Pandas when the data is loaded into the dataframe. The second column for each dataframe will always be '%%.' This is a placeholder column that exists only to be used during export. Export will look for the column and comment out any row that includes a single '%.' This is to preserve the exact order of the radial file that was generated at the CODAR site.

In [9]:
r.data

LOND       LATD   VELU    VELV  VFLG  ...     RNGE   BEAR    VELO   HEAD  SPRC
0   -73.972291  40.421208 -0.031  -1.788   128  ...   6.0406    1.0   1.788  181.0     2
1   -73.966093  40.420918 -0.358  -3.403   128  ...   6.0406    6.0   3.422  186.0     2
2   -73.959952  40.420215 -2.629 -13.516   128  ...   6.0406   11.0  13.769  191.0     2
3   -73.953915  40.419107 -3.948 -13.758   128  ...   6.0406   16.0  14.313  196.0     2
4   -73.942334  40.415706  5.460  11.185     0  ...   6.0406   26.0 -12.447  206.0     2
..         ...        ...    ...     ...   ...  ...      ...    ...     ...    ...   ...
728 -74.313784  39.828457 -3.383  -7.005   128  ...  66.4466  206.0  -7.779   25.8    22
729 -73.160940  40.298568  0.154  -0.018     0  ...  69.4669   96.0  -0.155  276.5    23
730 -73.241405  40.090246 -0.349   0.174     0  ...  69.4669  116.0   0.390  296.5    23
731 -73.275802  40.042493 -1.726   1.056     0  ...  69.4669  121.0   2.023  301.5    23
732 -74.196994  39.765210 -0.637  -2.244   128  ...  69.4669  196.0  -2.333   15.9    23

[733 rows x 18 columns]

In [10]:
r.diagnostics_hardware

TIME  RTMP  MTMP  XTRP   RUNT  ...  TDAY  THRS  TMIN  TSEC            datetime
0  -35.0    23    35     0  35635  ...     1     0    25     0 2019-01-01 00:25:00
1  -30.0    23    35     0  35905  ...     1     0    30     0 2019-01-01 00:30:00
2  -25.0    23    35     0  36204  ...     1     0    35     0 2019-01-01 00:35:00
3  -20.0    23    35     0  36504  ...     1     0    40     0 2019-01-01 00:40:00
4  -15.0    23    35     0  36803  ...     1     0    45     0 2019-01-01 00:45:00
5  -10.0    23    35     0  37103  ...     1     0    50     0 2019-01-01 00:50:00
6   -5.0    23    35     0  37402  ...     1     0    55     0 2019-01-01 00:55:00
7    0.0    23    35     0  37702  ...     1     1     0     0 2019-01-01 01:00:00
8    5.0    23    35     0  38001  ...     1     1     5     0 2019-01-01 01:05:00
9   10.0    23    35     0  38300  ...     1     1    10     0 2019-01-01 01:10:00
10  15.0    23    35     0  38600  ...     1     1    15     0 2019-01-01 01:15:00
11  20.0    23    35     0  38899  ...     1     1    20     0 2019-01-01 01:20:00
12  25.0    23    35     0  39199  ...     1     1    25     0 2019-01-01 01:25:00
13  30.0    23    35     0  39498  ...     1     1    30     0 2019-01-01 01:30:00
14  35.0    23    35     0  39797  ...     1     1    35     0 2019-01-01 01:35:00

[15 rows x 34 columns]

In [11]:
r.diagnostics_radial

TIME   AMP1   AMP2  PH13  PH23  ...  TDAY  THRS  TMIN  TSEC            datetime
0 -1800  0.261  0.455  58.1  79.5  ...     1     0    30     0 2019-01-01 00:30:00
1 -1200  0.248  0.466  58.2  78.4  ...     1     0    40     0 2019-01-01 00:40:00
2  -600  0.239  0.449  57.9  80.1  ...     1     0    50     0 2019-01-01 00:50:00
3     0  0.240  0.445  59.0  80.4  ...     1     1     0     0 2019-01-01 01:00:00
4   600  0.247  0.443  58.1  79.6  ...     1     1    10     0 2019-01-01 01:10:00
5  1200  0.248  0.442  58.3  78.8  ...     1     1    20     0 2019-01-01 01:20:00
6  1800  0.239  0.480  58.8  79.3  ...     1     1    30     0 2019-01-01 01:30:00

[7 rows x 32 columns]

# Radial Quality Control Tests

We have implemented eight QARTOD radial tests

## QC Test Initialization
You must tell the instance that you are about to execute the qc tests. This is necessary in order to preserve the original .ruv structure of the raw radial files. This way, we can still utilize the manufacturer's tools as intended.

In [12]:
r.initialize_qc()

## Syntax

**Description:** A collection of tests ensuring proper formatting and existence of fields within a radial file.

**Test specifications:** Acceptable files types, site codes, coordinates, APM names, etc., must be presented. For example, the national network performs the following suite of tests:
* All radial files acquired by HFRNet portals report the data timestamp in the filename.
The filename timestamp must not be any more than 72 hours in the future relative to the
portals’ system time.
* The file name timestamp must match the timestamp reported within the file.
* Radial data tables (Lon, Lat, U, V, ...) must not be empty.
* Radial data table columns stated must match the number of columns reported for each
row (a useful test for catching partial or corrupted files).
* The site location must be within range: − 180 ≤ Longitude ≤ 180 − 90 ≤ Latitude ≤ 90.
* As a minimum, the following metadata must be defined:
    * File type (LLUV)
    * Site code
    * Timestamp
    * Site coordinates
    * Antenna pattern type (measured or idealized)
    * Time zone (only Coordinated Universal Time or Greenwich Mean Time accepted)

If a radial file is successfully loaded by the Radial class that file automatically passes the QARTOD Syntax test. 

In [16]:
r.qc_qartod_syntax()

In [17]:
r.data.head()

LOND       LATD   VELU    VELV  VFLG  ...  BEAR    VELO   HEAD  SPRC  QC06
0 -73.972291  40.421208 -0.031  -1.788   128  ...   1.0   1.788  181.0     2     4
1 -73.966093  40.420918 -0.358  -3.403   128  ...   6.0   3.422  186.0     2     4
2 -73.959952  40.420215 -2.629 -13.516   128  ...  11.0  13.769  191.0     2     4
3 -73.953915  40.419107 -3.948 -13.758   128  ...  16.0  14.313  196.0     2     4
4 -73.942334  40.415706  5.460  11.185     0  ...  26.0 -12.447  206.0     2     4

[5 rows x 19 columns]

## Maximum Velocity Threshold
Ensures that a radial currend speed is not unrealistically high.

**Description:** The maximum radial speed threshold (RSPDMAX) represents the maximum reasonable surface radial
velocity for the given domain.

**Test Specifications:** The maximum total speed threshold is 1 m/s for the West
Coast of the United States and 3 m/s for the East/Gulf Coast domain. The threshold must vary by region. For
example, the presence of the Gulf Stream dictates the higher threshold on the East Coast.

**Default Max Threshold:** 250 cm/s

Flags (VLOC): 
* Fail = 4
    * Radial current speed exceeds the maximum radial speed threshold
* Pass = 1
    * Radial current speed is less than or equal to the maximum radial speed threshold.

In [31]:
help(r.qc_qartod_maximum_velocity)

Help on method qc_qartod_maximum_velocity in module hfradar.src.radials:

qc_qartod_maximum_velocity(radial_max_speed=250, radial_high_speed=150) method of hfradar.src.radials.Radial instance
    Integrated Ocean Observing System (IOOS) Quality Assurance of Real-Time Oceanographic Data (QARTOD)
    Max Threshold (Test 7)
    Ensures that a radial current speed is not unrealistically high.
    
    The maximum radial speed threshold (RSPDMAX) represents the maximum reasonable surface radial velocity
    for the given domain.
    
    Link: https://ioos.noaa.gov/ioos-in-action/manual-real-time-quality-control-high-frequency-radar-surface-current-data/
    :param threshold: Maximum Radial Speed (cm/s)
    :return:



In [18]:
r.qc_qartod_maximum_velocity(radial_max_speed=250, radial_high_speed=150) #cm/s

In [19]:
r.data.head()

LOND       LATD   VELU    VELV  VFLG  ...    VELO   HEAD  SPRC  QC06  QC07
0 -73.972291  40.421208 -0.031  -1.788   128  ...   1.788  181.0     2     4     1
1 -73.966093  40.420918 -0.358  -3.403   128  ...   3.422  186.0     2     4     1
2 -73.959952  40.420215 -2.629 -13.516   128  ...  13.769  191.0     2     4     1
3 -73.953915  40.419107 -3.948 -13.758   128  ...  14.313  196.0     2     4     1
4 -73.942334  40.415706  5.460  11.185     0  ... -12.447  206.0     2     4     1

[5 rows x 20 columns]

## Valid Location 
Removes radial vectors placed over land or in other unmeasureable areas.

**Description:** Radial vector coordinates are checked against a reference file containing information about which locations
are over land or in an unmeasurable area (for example, behind an island or point of land). Radials in these
areas will be flagged with a code (FLOC) in the radial file (+128 in CODAR radial files) and are not included in
total vector calculations.

**Test Specifications:**
For CODAR systems, the reference file is called AngSeg_XXXX.txt, where XXXX is the four-letter site code of the station and is located in the “RadialConfigs” folder. These vectors receive a code of +128 in the flag column of the radial text file. BF systems use pre-set grid locations for radials.

**Default Location Flag:** 128 (corresponds to CODAR AngSeg flag)

Flags (VLOC): 
* Fail = 4
    * Radial contains a user-defined location flag code in the radial file
* Pass = 1
    * Radial does not contain a user-defined location flag code in the radial file.

In [20]:
r.qc_qartod_valid_location()

In [21]:
r.data.head()

LOND       LATD   VELU    VELV  VFLG  ...   HEAD  SPRC  QC06  QC07  QC08
0 -73.972291  40.421208 -0.031  -1.788   128  ...  181.0     2     4     1     4
1 -73.966093  40.420918 -0.358  -3.403   128  ...  186.0     2     4     1     4
2 -73.959952  40.420215 -2.629 -13.516   128  ...  191.0     2     4     1     4
3 -73.953915  40.419107 -3.948 -13.758   128  ...  196.0     2     4     1     4
4 -73.942334  40.415706  5.460  11.185     0  ...  206.0     2     4     1     1

[5 rows x 21 columns]

## Radial Count
Rejects radials in files with low radial counts (poor radial map coverage)

**Description:** The number of radials (RCNT) in a radial file must be above a threshold value RCNT_MIN to pass the test and above a value RC_LOW to not be considered suspect. If the number of radials is below the minimum level, it indicates a problem with data collection. In this case, the file should be rejected and none of the radials used for total vector processing.

**Test Specifications:** The RC_LOW threshold may be based on the national
network performance metric threshold value of 300. The choice of 300 radial solutions came from grouping
radial files over a certain time period from all stations, looking at the cumulative density function for counts,
and selecting a value around 10%. However, this threshold does not work for all stations. A custom value for
a site might be found by following the same procedure for the individual station.

**Default Max Threshold:** min_radials = 150; low_radials = 300 

Flags (VLOC): 
* Fail = 4
    * Number of radials is less than min_radials
* Suspect = 3
    * Number of radials is greater than min_radials but less than or equal to low_radials
* Pass = 1
    * Number of radials is greater than low_radials.
    
This will not add an extra column to the file. Rather it will add the test result a new key, qc_qartod_radial_count, to the header file of a newly exported radial.

In [22]:
r.qc_qartod_radial_count(radial_low_count=140, radial_min_count=50)

In [23]:
r.data

LOND       LATD   VELU    VELV  VFLG  ...  SPRC  QC06  QC07  QC08  QC09
0   -73.972291  40.421208 -0.031  -1.788   128  ...     2     4     1     4     1
1   -73.966093  40.420918 -0.358  -3.403   128  ...     2     4     1     4     1
2   -73.959952  40.420215 -2.629 -13.516   128  ...     2     4     1     4     1
3   -73.953915  40.419107 -3.948 -13.758   128  ...     2     4     1     4     1
4   -73.942334  40.415706  5.460  11.185     0  ...     2     4     1     1     1
..         ...        ...    ...     ...   ...  ...   ...   ...   ...   ...   ...
728 -74.313784  39.828457 -3.383  -7.005   128  ...    22     4     1     4     1
729 -73.160940  40.298568  0.154  -0.018     0  ...    23     4     1     1     1
730 -73.241405  40.090246 -0.349   0.174     0  ...    23     4     1     1     1
731 -73.275802  40.042493 -1.726   1.056     0  ...    23     4     1     1     1
732 -74.196994  39.765210 -0.637  -2.244   128  ...    23     4     1     4     1

[733 rows x 22 columns]

## Spatial Median 
Reduces outlier velocities in radials.

**Description:** 
RV is the radial velocity
NV is a set of radial velocities for neighboring radial cells (cells within radius of 'radial_smed_range_cell_limit' * Range Step (km)and whose vector bearing (angle of arrival at site) is also within 'radial_smed_angular_limit' degrees of the source vector's bearing)

**Test Specifications:** Required to pass the test: |RV - median(NV)| <= radial_smed_current_difference

Flags (VLOC): 
* Fail = 4
    * Difference between the vector velocity and the median velocity is greater than the threshold.
* Pass = 1
    * If the difference between the vector velocity and the median velocity is less or equal to the threshold, the vector value is CHANGED to the median value.

In [24]:
r.qc_qartod_spatial_median(radial_smed_range_cell_limit=2.1, radial_smed_angular_limit=10, radial_smed_current_difference=30)

/Users/mikesmith/miniconda3/envs/hfradar/lib/python3.7/site-packages/numpy/lib/nanfunctions.py:1120: RuntimeWarning: All-NaN slice encountered
  overwrite_input=overwrite_input)


## Temporal Gradient  
Checks for satisfactory temporal rate of change of radial components.

**Description:** 
Test determines whether changes between successive radial velocity measurements at a particular range and bearing cell are within an acceptable range. GRADIENT_TEMP = |Rt-1 - Rt|

**Test Specifications:** Required to pass the test: |RV - median(NV)| <= radial_smed_current_difference

Flags (VLOC): 
* Fail = 4
    * The temporal change between successive radial velocities exceeds the gradient failure threshold.

* Suspect = 3
    * The temporal change between successive radial velocities is less than the gradient failure threshold but exceeds the gradient warn threshold.
    
* Pass = 1
    * The temporal change between successive radial velocities is less than the gradient warn threshold.

In [25]:
# r0 set so we can demonstrate temporal gradient test
r0 = '../hfradar/data/radials/ruv/SEAB/RDLi_SEAB_2019_01_01_0000.ruv'

In [26]:
r.qc_qartod_temporal_gradient(r0, gradient_temp_fail=54, gradient_temp_warn=36)

In [27]:
r.data

LOND       LATD   VELU    VELV  VFLG  ...  QC07  QC08  QC09  QC10  QC11
0   -73.972291  40.421208 -0.031  -1.788   128  ...     1     4     1     1     1
1   -73.966093  40.420918 -0.358  -3.403   128  ...     1     4     1     1     2
2   -73.959952  40.420215 -2.629 -13.516   128  ...     1     4     1     1     1
3   -73.953915  40.419107 -3.948 -13.758   128  ...     1     4     1     1     1
4   -73.942334  40.415706  5.460  11.185     0  ...     1     1     1     1     1
..         ...        ...    ...     ...   ...  ...   ...   ...   ...   ...   ...
728 -74.313784  39.828457 -3.383  -7.005   128  ...     1     4     1     1     2
729 -73.160940  40.298568  0.154  -0.018     0  ...     1     1     1     1     2
730 -73.241405  40.090246 -0.349   0.174     0  ...     1     1     1     1     1
731 -73.275802  40.042493 -1.726   1.056     0  ...     1     1     1     1     1
732 -74.196994  39.765210 -0.637  -2.244   128  ...     1     4     1     1     2

[733 rows x 24 columns]

## Average Radial Bearing
Check that the average radial bearing remains relatively constant (Roarty et al. 2012).

**Description:** 
It is expected that the average of all radial velocity bearings AVG_RAD_BEAR obtained during a sample interval (e.g., 1 hour) should be close to a reference bearing REF_RAD_BEAR and not vary beyond warning or failure thresholds.

**Test Specifications:**  RAD_BEAR_DIF_FAIL =30°, RAD_BEAR DIF_WARN = 15°

Flags (VLOC): 
* Fail = 4
    * The absolute difference between the average radial bearing and a reference bearing exceeds a failure threshold.

* Suspect = 3
    * The absolute difference between the average radial bearing and a reference bearing is less than the failure threshold but exceeds the warning threshold.
    
* Pass = 1
    * The absolute difference between the average radial bearing and a reference bearing is less than the warning threshold.

In [28]:
r.qc_qartod_avg_radial_bearing(reference_bearing=151, warning_threshold=15, failure_threshold=30)

In [29]:
r.data

LOND       LATD   VELU    VELV  VFLG  ...  QC08  QC09  QC10  QC11  QC12
0   -73.972291  40.421208 -0.031  -1.788   128  ...     4     1     1     1     1
1   -73.966093  40.420918 -0.358  -3.403   128  ...     4     1     1     2     1
2   -73.959952  40.420215 -2.629 -13.516   128  ...     4     1     1     1     1
3   -73.953915  40.419107 -3.948 -13.758   128  ...     4     1     1     1     1
4   -73.942334  40.415706  5.460  11.185     0  ...     1     1     1     1     1
..         ...        ...    ...     ...   ...  ...   ...   ...   ...   ...   ...
728 -74.313784  39.828457 -3.383  -7.005   128  ...     4     1     1     2     1
729 -73.160940  40.298568  0.154  -0.018     0  ...     1     1     1     2     1
730 -73.241405  40.090246 -0.349   0.174     0  ...     1     1     1     1     1
731 -73.275802  40.042493 -1.726   1.056     0  ...     1     1     1     1     1
732 -74.196994  39.765210 -0.637  -2.244   128  ...     4     1     1     2     1

[733 rows x 25 columns]

In [33]:
r.data['VELU'][r.data['VELU'] > 30]

154    31.236
566    31.061
Name: VELU, dtype: float64

## Primary Flag 
Create primary flag column that gives the highest level of failure for each row.


In [30]:
r.qc_qartod_primary_flag()

Finally, lets export the qc'ed radial file back to the CODAR .ruv format

In [ ]:
# r.clean_header()

In [ ]:
save_dir = '../codar_processing/data/radials_qc/'
r.export(os.path.join(save_dir, 'ruv', r.file_name), 'radial')